/*
Deployment script for WideWorldImportersNew3

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "WideWorldImportersNew3"
:setvar DefaultFilePrefix "WideWorldImportersNew3"
:setvar DefaultDataPath "F:\Data\"
:setvar DefaultLogPath "F:\Logs\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping [Application].[Cities].[NonClusteredIndex-20200802-110247]...';


GO
DROP INDEX [NonClusteredIndex-20200802-110247]
    ON [Application].[Cities];


GO
PRINT N'Update complete.';


GO
