CREATE PROCEDURE [data].[Populate_dbo_DimProductCategory]
AS
BEGIN
/*
	Table's data:    [dbo].[DimProductCategory]
	Data Source:     [DEV19].[ContosoRetailDW]
	Created on:      16/08/2020 00:55:00
	Scripted by:     DEV19\Administrator
	Generated by:    Data Script Writer - ver. 2.2.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[DimProductCategory]';

IF OBJECT_ID('tempdb.dbo.#dbo_DimProductCategory') IS NOT NULL DROP TABLE #dbo_DimProductCategory;
SELECT * INTO #dbo_DimProductCategory FROM [dbo].[DimProductCategory] WHERE 0=1;

SET IDENTITY_INSERT #dbo_DimProductCategory ON;

INSERT INTO #dbo_DimProductCategory 
 ([ProductCategoryKey], [ProductCategoryLabel], [ProductCategoryName], [ProductCategoryDescription], [ETLLoadID], [LoadDate], [UpdateDate])
SELECT CAST([ProductCategoryKey] AS int) AS [ProductCategoryKey], [ProductCategoryLabel], [ProductCategoryName], [ProductCategoryDescription], [ETLLoadID], [LoadDate], [UpdateDate] FROM 
(VALUES
	  (1,	N'01',	N'Audio',	N'Audio',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (2,	N'02',	N'TV and Video',	N'TV and Video',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (3,	N'03',	N'Computers',	N'Computers',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (4,	N'04',	N'Cameras and camcorders ',	N'Cameras and camcorders ',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (5,	N'05',	N'Cell phones',	N'Cell phones',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (6,	N'06',	N'Music, Movies and Audio Books',	N'Music, Movies and Audio Books',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (7,	N'07',	N'Games and Toys',	N'Games and Toys',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (8,	N'08',	N'Home Appliances',	N'Home Appliances',	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
) as v ([ProductCategoryKey], [ProductCategoryLabel], [ProductCategoryName], [ProductCategoryDescription], [ETLLoadID], [LoadDate], [UpdateDate]);


SET IDENTITY_INSERT #dbo_DimProductCategory OFF;

SET IDENTITY_INSERT [dbo].[DimProductCategory] ON;


WITH cte_data as (SELECT CAST([ProductCategoryKey] AS int) AS [ProductCategoryKey], [ProductCategoryLabel], [ProductCategoryName], [ProductCategoryDescription], [ETLLoadID], [LoadDate], [UpdateDate] FROM [#dbo_DimProductCategory])
MERGE [dbo].[DimProductCategory] as t
USING cte_data as s
	ON t.[ProductCategoryKey] = s.[ProductCategoryKey]
WHEN NOT MATCHED BY target THEN
	INSERT ([ProductCategoryKey], [ProductCategoryLabel], [ProductCategoryName], [ProductCategoryDescription], [ETLLoadID], [LoadDate], [UpdateDate])
	VALUES (s.[ProductCategoryKey], s.[ProductCategoryLabel], s.[ProductCategoryName], s.[ProductCategoryDescription], s.[ETLLoadID], s.[LoadDate], s.[UpdateDate])
WHEN MATCHED THEN 
	UPDATE SET 
	[ProductCategoryLabel] = s.[ProductCategoryLabel], [ProductCategoryName] = s.[ProductCategoryName], [ProductCategoryDescription] = s.[ProductCategoryDescription], [ETLLoadID] = s.[ETLLoadID], [LoadDate] = s.[LoadDate], [UpdateDate] = s.[UpdateDate]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[DimProductCategory] OFF;

DROP TABLE #dbo_DimProductCategory;

-- End data of table: [dbo].[DimProductCategory] --
END
GO
