CREATE PROCEDURE [data].[Populate_dbo_DimProductSubcategory]
AS
BEGIN
/*
	Table's data:    [dbo].[DimProductSubcategory]
	Data Source:     [DEV19].[ContosoRetailDW]
	Created on:      16/08/2020 00:55:01
	Scripted by:     DEV19\Administrator
	Generated by:    Data Script Writer - ver. 2.2.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[DimProductSubcategory]';

IF OBJECT_ID('tempdb.dbo.#dbo_DimProductSubcategory') IS NOT NULL DROP TABLE #dbo_DimProductSubcategory;
SELECT * INTO #dbo_DimProductSubcategory FROM [dbo].[DimProductSubcategory] WHERE 0=1;

SET IDENTITY_INSERT #dbo_DimProductSubcategory ON;

INSERT INTO #dbo_DimProductSubcategory 
 ([ProductSubcategoryKey], [ProductSubcategoryLabel], [ProductSubcategoryName], [ProductSubcategoryDescription], [ProductCategoryKey], [ETLLoadID], [LoadDate], [UpdateDate])
SELECT CAST([ProductSubcategoryKey] AS int) AS [ProductSubcategoryKey], [ProductSubcategoryLabel], [ProductSubcategoryName], [ProductSubcategoryDescription], [ProductCategoryKey], [ETLLoadID], [LoadDate], [UpdateDate] FROM 
(VALUES
	  (1,	N'0101',	N'MP4&MP3',	N'MP4&MP3',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (2,	N'0102',	N'Recorder',	N'Recorder',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (3,	N'0103',	N'Radio',	N'Radio',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (4,	N'0104',	N'Recording Pen',	N'Recording Pen',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (5,	N'0105',	N'Headphones',	N'Headphones',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (6,	N'0106',	N'Bluetooth Headphones',	N'Bluetooth Headphones',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (7,	N'0107',	N'Speakers',	N'Speakers',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (8,	N'0108',	N'Audio Accessories',	N'Audio Accessories',	1,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (9,	N'0201',	N'Televisions',	N'Televisions',	2,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (10,	N'0202',	N'VCD & DVD',	N'VCD & DVD',	2,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (11,	N'0203',	N'Home Theater System',	N'Home Theater System',	2,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (13,	N'0205',	N'Car Video',	N'Car Video',	2,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (14,	N'0206',	N'TV & Video Accessories',	N'TV & Video Accessories',	2,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (15,	N'0301',	N'Laptops',	N'Laptops',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (16,	N'0302',	N'Netbooks',	N'Netbooks',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (17,	N'0303',	N'Desktops',	N'Desktops',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (18,	N'0304',	N'Monitors',	N'Monitors',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (19,	N'0305',	N'Projectors & Screens',	N'Projectors & Screens',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (20,	N'0306',	N'Printers, Scanners & Fax',	N'Printers, Scanners & Fax',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (21,	N'0307',	N'Computer Setup & Service',	N'Computer Setup & Service',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (22,	N'0308',	N'Computers Accessories',	N'Computers Accessories',	3,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (23,	N'0401',	N'Digital Cameras',	N'Digital Cameras',	4,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (24,	N'0402',	N'Digital SLR Cameras',	N'Digital SLR Cameras',	4,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (25,	N'0403',	N'Film Cameras',	N'Film Cameras',	4,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (27,	N'0405',	N'Camcorders',	N'Camcorders',	4,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (28,	N'0406',	N'Cameras & Camcorders Accessories',	N'Cameras & Camcorders Accessories',	4,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (29,	N'0501',	N'Home & Office Phones',	N'Home & Office Phones',	5,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (31,	N'0503',	N'Touch Screen Phones ',	N'Touch Screen Phones ',	5,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (32,	N'0504',	N'Smart phones & PDAs ',	N'Smart phones & PDAs ',	5,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (33,	N'0505',	N'Cell phones Accessories',	N'Cell phones Accessories',	5,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (34,	N'0601',	N'Music CD',	N'Music CD',	6,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (35,	N'0602',	N'Movie DVD',	N'Movie DVD',	6,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (36,	N'0603',	N'Audio Books',	N'Audio Books',	6,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (38,	N'0701',	N'Boxed Games',	N'Boxed Games',	7,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (39,	N'0702',	N'Download Games',	N'Download Games',	7,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (40,	N'0703',	N'Games Accessories',	N'Games Accessories',	7,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (41,	N'0801',	N'Washers & Dryers',	N'Washers & Dryers',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (42,	N'0802',	N'Refrigerators',	N'Refrigerators',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (43,	N'0803',	N'Microwaves',	N'Microwaves',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (44,	N'0804',	N'Water Heaters',	N'Water Heaters',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (45,	N'0805',	N'Coffee Machines',	N'Coffee Machines',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (46,	N'0806',	N'Lamps',	N'Lamps',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (47,	N'0807',	N'Air Conditioners',	N'Air Conditioners',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
	, (48,	N'0808',	N'Fans',	N'Fans',	8,	1,	'20090707 00:00:00.000',	'20090707 00:00:00.000')
) as v ([ProductSubcategoryKey], [ProductSubcategoryLabel], [ProductSubcategoryName], [ProductSubcategoryDescription], [ProductCategoryKey], [ETLLoadID], [LoadDate], [UpdateDate]);


SET IDENTITY_INSERT #dbo_DimProductSubcategory OFF;

SET IDENTITY_INSERT [dbo].[DimProductSubcategory] ON;


WITH cte_data as (SELECT CAST([ProductSubcategoryKey] AS int) AS [ProductSubcategoryKey], [ProductSubcategoryLabel], [ProductSubcategoryName], [ProductSubcategoryDescription], [ProductCategoryKey], [ETLLoadID], [LoadDate], [UpdateDate] FROM [#dbo_DimProductSubcategory])
MERGE [dbo].[DimProductSubcategory] as t
USING cte_data as s
	ON t.[ProductSubcategoryKey] = s.[ProductSubcategoryKey]
WHEN NOT MATCHED BY target THEN
	INSERT ([ProductSubcategoryKey], [ProductSubcategoryLabel], [ProductSubcategoryName], [ProductSubcategoryDescription], [ProductCategoryKey], [ETLLoadID], [LoadDate], [UpdateDate])
	VALUES (s.[ProductSubcategoryKey], s.[ProductSubcategoryLabel], s.[ProductSubcategoryName], s.[ProductSubcategoryDescription], s.[ProductCategoryKey], s.[ETLLoadID], s.[LoadDate], s.[UpdateDate])
WHEN MATCHED THEN 
	UPDATE SET 
	[ProductSubcategoryLabel] = s.[ProductSubcategoryLabel], [ProductSubcategoryName] = s.[ProductSubcategoryName], [ProductSubcategoryDescription] = s.[ProductSubcategoryDescription], [ProductCategoryKey] = s.[ProductCategoryKey], [ETLLoadID] = s.[ETLLoadID], [LoadDate] = s.[LoadDate], [UpdateDate] = s.[UpdateDate]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[DimProductSubcategory] OFF;

DROP TABLE #dbo_DimProductSubcategory;

-- End data of table: [dbo].[DimProductSubcategory] --
END
GO
